FROM python:3.11-slim

WORKDIR /app

COPY requirements.docker.txt .

RUN pip install --no-cache-dir -r requirements.docker.txt

COPY dashboard ./dashboard
COPY src ./src
COPY models ./models
COPY data ./data

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py", "--server.address=0.0.0.0", "--server.port=8501"]